//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Assignment
    {
        public int AssignId { get; set; }
        public Nullable<System.DateTime> AssignDate { get; set; }
        public Nullable<System.TimeSpan> AssignTime { get; set; }
        public Nullable<int> Pid { get; set; }
    
        public virtual PickupBoy PickupBoy { get; set; }
    }
}
